# basic
# ============================================================================
# if your site is serving on https://xxx.github.io, set `baseurl: /`
# if your site is serving on https://xxx.github.io/path, set `baseurl: /path`
url: "https://bny.otfo.cc"
baseurl: ""

# site title
title: Bny

# site favicon, absolute path required
favicon: /assets/img/favicon.jpg

# home button image, absolute path requried
avatar: /assets/img/avatar.jpg
# specify meaningful description for your avatar
avatarInfo: "..."

header_image_1: /assets/img/header_image_1.jpg
header_image_2: /assets/img/header_image_2.jpg
header_image_3: /assets/img/header_image_3.jpg

# permalink: /:year-:month-:day-:title/


# default variables for post-type page
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      comment: true

# sass
# ============================================================================
sass:
  sass_dir: _sass
  style: compressed


plugins:
  - jekyll-admin
  - jekyll-assets



# exclude none site related files
# ============================================================================
exclude:
  - README.md
  - LICENSE
  - github
  - package.json
  - package-lock.json
  - node_modules


# google analytics
# ============================================================================
# turn it off -> ga: false
ga: false


# disqus
# ============================================================================
# turn it off for all posts -> disqus: false
# turn it off for a particular post -> add `comment: false` to post front matter
disqus: otfo







